"""GENERATED typed models, one per table, enum and wire shape.

Never hand-edited: CI regenerates this package and compares, and a hand
edit is `SCHEMA_GENERATED_DRIFT`. This package imports only `pydantic`,
enforced by the `generated-purity` contract, and holds no business logic.

The error registry is **not** here -- it lives in `adopt_obs.errors`,
because it is needed before this package is first generated (CR-21).
"""

# GENERATED FROM schema/canonical.yaml -- DO NOT EDIT.
# Regenerate with `adopt-schema generate`. A hand edit is SCHEMA_GENERATED_DRIFT
# and CI fails on it, because a hand-edited realization means the manifest has
# silently stopped being the single source of truth.

from typing import Final

from pydantic import BaseModel

from adopt_model._enums import (
    ApprovalSubject,
    Archetype,
    AssignmentReason,
    AuthorityClass,
    BindingStatus,
    ChangeSource,
    ConfidenceLabel,
    ConnectorMode,
    ConnectorStatus,
    ControlPlane,
    DeathCause,
    DecidedBy,
    DeploymentMode,
    DiffMethod,
    Disposition,
    EscalationBranch,
    EscalationChannel,
    EscalationStatus,
    FreshnessState,
    HeartbeatOutcome,
    IdentityKind,
    IdentityStatus,
    ImpactClass,
    ItemKind,
    KnowledgePlane,
    LifecycleState,
    LocatorRung,
    OwnershipScope,
    ProbeDefinitionStatus,
    ProbeOutcome,
    ReviewResolution,
    SafePath,
    SensorHealth,
    SensorKind,
    SilentRepairState,
    SourceType,
    Tier,
    ValueEventType,
    Verification,
)
from adopt_model._tables import (
    Approval,
    AudienceTag,
    AuditEvent,
    BaselineVersion,
    Binding,
    BindingRevision,
    ChangeEvent,
    Classification,
    ClassifierVersion,
    Conflict,
    Connector,
    DeathCondition,
    Engagement,
    Environment,
    Escalation,
    Firm,
    Identity,
    IdentityRevision,
    KnowledgeItem,
    KnowledgeRevision,
    ObservabilityBoundary,
    OwnershipAssignment,
    ProbeDefinition,
    ProbeDefinitionRevision,
    ProbeObservation,
    ProbeRun,
    Provenance,
    ReviewBatch,
    ReviewItem,
    SchemaMeta,
    Sensor,
    SensorHeartbeat,
    SilentRepairEligibility,
    System,
    SystemLifecycleEvent,
    ValueBaseline,
    ValueEvent,
)

__all__ = [
    "MODEL_FOR_TABLE",
    "Approval",
    "ApprovalSubject",
    "Archetype",
    "AssignmentReason",
    "AudienceTag",
    "AuditEvent",
    "AuthorityClass",
    "BaselineVersion",
    "Binding",
    "BindingRevision",
    "BindingStatus",
    "ChangeEvent",
    "ChangeSource",
    "Classification",
    "ClassifierVersion",
    "ConfidenceLabel",
    "Conflict",
    "Connector",
    "ConnectorMode",
    "ConnectorStatus",
    "ControlPlane",
    "DeathCause",
    "DeathCondition",
    "DecidedBy",
    "DeploymentMode",
    "DiffMethod",
    "Disposition",
    "Engagement",
    "Environment",
    "Escalation",
    "EscalationBranch",
    "EscalationChannel",
    "EscalationStatus",
    "Firm",
    "FreshnessState",
    "HeartbeatOutcome",
    "Identity",
    "IdentityKind",
    "IdentityRevision",
    "IdentityStatus",
    "ImpactClass",
    "ItemKind",
    "KnowledgeItem",
    "KnowledgePlane",
    "KnowledgeRevision",
    "LifecycleState",
    "LocatorRung",
    "ObservabilityBoundary",
    "OwnershipAssignment",
    "OwnershipScope",
    "ProbeDefinition",
    "ProbeDefinitionRevision",
    "ProbeDefinitionStatus",
    "ProbeObservation",
    "ProbeOutcome",
    "ProbeRun",
    "Provenance",
    "ReviewBatch",
    "ReviewItem",
    "ReviewResolution",
    "SafePath",
    "SchemaMeta",
    "Sensor",
    "SensorHealth",
    "SensorHeartbeat",
    "SensorKind",
    "SilentRepairEligibility",
    "SilentRepairState",
    "SourceType",
    "System",
    "SystemLifecycleEvent",
    "Tier",
    "ValueBaseline",
    "ValueEvent",
    "ValueEventType",
    "Verification",
]

#: Canonical table name -> the model that validates one of its rows.
#: Generated because the correspondence is the manifest's, not a
#: convention a caller should re-derive from a class name: the export
#: writer, the importer and the store all need it, and three
#: reconstructions of one mapping are three places for it to drift.
MODEL_FOR_TABLE: Final[dict[str, type[BaseModel]]] = {
    "approval": Approval,
    "audience_tag": AudienceTag,
    "audit_event": AuditEvent,
    "baseline_version": BaselineVersion,
    "binding": Binding,
    "binding_revision": BindingRevision,
    "change_event": ChangeEvent,
    "classification": Classification,
    "classifier_version": ClassifierVersion,
    "conflict": Conflict,
    "connector": Connector,
    "death_condition": DeathCondition,
    "engagement": Engagement,
    "environment": Environment,
    "escalation": Escalation,
    "firm": Firm,
    "identity": Identity,
    "identity_revision": IdentityRevision,
    "knowledge_item": KnowledgeItem,
    "knowledge_revision": KnowledgeRevision,
    "observability_boundary": ObservabilityBoundary,
    "ownership_assignment": OwnershipAssignment,
    "probe_definition": ProbeDefinition,
    "probe_definition_revision": ProbeDefinitionRevision,
    "probe_observation": ProbeObservation,
    "probe_run": ProbeRun,
    "provenance": Provenance,
    "review_batch": ReviewBatch,
    "review_item": ReviewItem,
    "schema_meta": SchemaMeta,
    "sensor": Sensor,
    "sensor_heartbeat": SensorHeartbeat,
    "silent_repair_eligibility": SilentRepairEligibility,
    "system": System,
    "system_lifecycle_event": SystemLifecycleEvent,
    "value_baseline": ValueBaseline,
    "value_event": ValueEvent,
}
