"""GENERATED typed models, one per table, enum and wire shape.

Never hand-edited: CI regenerates this package and compares, and a hand
edit is `SCHEMA_GENERATED_DRIFT`. This package imports only `pydantic`,
enforced by the `generated-purity` contract, and holds no business logic.

The error registry is **not** here -- it lives in `adopt_obs.errors`,
because it is needed before this package is first generated (CR-21).
"""

# GENERATED FROM schema/canonical.yaml -- DO NOT EDIT.
# Regenerate with `adopt-schema generate`. A hand edit is SCHEMA_GENERATED_DRIFT
# and CI fails on it, because a hand-edited realization means the manifest has
# silently stopped being the single source of truth.

from adopt_model._enums import (
    ApprovalSubject,
    Archetype,
    AssignmentReason,
    AuthorityClass,
    BindingStatus,
    ChangeSource,
    ConfidenceLabel,
    ConnectorMode,
    ConnectorStatus,
    ControlPlane,
    DeathCause,
    DecidedBy,
    DeploymentMode,
    DiffMethod,
    Disposition,
    EscalationBranch,
    EscalationChannel,
    EscalationStatus,
    FreshnessState,
    HeartbeatOutcome,
    IdentityKind,
    IdentityStatus,
    ImpactClass,
    ItemKind,
    KnowledgePlane,
    LifecycleState,
    LocatorRung,
    OwnershipScope,
    ProbeOutcome,
    ReviewResolution,
    SafePath,
    SensorHealth,
    SensorKind,
    SilentRepairState,
    SourceType,
    Tier,
    ValueEventType,
    Verification,
)
from adopt_model._tables import (
    Approval,
    AudienceTag,
    AuditEvent,
    BaselineVersion,
    Binding,
    BindingRevision,
    ChangeEvent,
    Classification,
    ClassifierVersion,
    Conflict,
    Connector,
    DeathCondition,
    Engagement,
    Environment,
    Escalation,
    Firm,
    Identity,
    IdentityRevision,
    KnowledgeItem,
    KnowledgeRevision,
    ObservabilityBoundary,
    OwnershipAssignment,
    ProbeDefinition,
    ProbeDefinitionRevision,
    ProbeObservation,
    ProbeRun,
    Provenance,
    ReviewBatch,
    ReviewItem,
    SchemaMeta,
    Sensor,
    SensorHeartbeat,
    SilentRepairEligibility,
    System,
    SystemLifecycleEvent,
    ValueBaseline,
    ValueEvent,
)

__all__ = [
    "Approval",
    "ApprovalSubject",
    "Archetype",
    "AssignmentReason",
    "AudienceTag",
    "AuditEvent",
    "AuthorityClass",
    "BaselineVersion",
    "Binding",
    "BindingRevision",
    "BindingStatus",
    "ChangeEvent",
    "ChangeSource",
    "Classification",
    "ClassifierVersion",
    "ConfidenceLabel",
    "Conflict",
    "Connector",
    "ConnectorMode",
    "ConnectorStatus",
    "ControlPlane",
    "DeathCause",
    "DeathCondition",
    "DecidedBy",
    "DeploymentMode",
    "DiffMethod",
    "Disposition",
    "Engagement",
    "Environment",
    "Escalation",
    "EscalationBranch",
    "EscalationChannel",
    "EscalationStatus",
    "Firm",
    "FreshnessState",
    "HeartbeatOutcome",
    "Identity",
    "IdentityKind",
    "IdentityRevision",
    "IdentityStatus",
    "ImpactClass",
    "ItemKind",
    "KnowledgeItem",
    "KnowledgePlane",
    "KnowledgeRevision",
    "LifecycleState",
    "LocatorRung",
    "ObservabilityBoundary",
    "OwnershipAssignment",
    "OwnershipScope",
    "ProbeDefinition",
    "ProbeDefinitionRevision",
    "ProbeObservation",
    "ProbeOutcome",
    "ProbeRun",
    "Provenance",
    "ReviewBatch",
    "ReviewItem",
    "ReviewResolution",
    "SafePath",
    "SchemaMeta",
    "Sensor",
    "SensorHealth",
    "SensorHeartbeat",
    "SensorKind",
    "SilentRepairEligibility",
    "SilentRepairState",
    "SourceType",
    "System",
    "SystemLifecycleEvent",
    "Tier",
    "ValueBaseline",
    "ValueEvent",
    "ValueEventType",
    "Verification",
]
