"""Stamp immutable SBOM and workflow identity facts into release artifacts."""

import argparse
import hashlib
import re
import sys
from pathlib import Path
from typing import Final

REPO_ROOT: Final[Path] = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT: Final[Path] = REPO_ROOT / "packages/adopt-cli/src/adopt_cli/_build_info.py"
BUILD_ID_RE: Final[re.Pattern[str]] = re.compile(
    r"^github:"
    r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?/"
    r"[A-Za-z0-9_.-]+:"
    r"[1-9][0-9]*:"
    r"[1-9][0-9]*:"
    r"(?:[0-9a-f]{40}|[0-9a-f]{64})$"
)


def render(sbom: Path, build_id: str) -> str:
    """Return the generated Python module for one release build."""
    if not sbom.is_file() or sbom.stat().st_size == 0:
        raise ValueError(f"SBOM is missing or empty: {sbom}")
    clean_build_id = build_id.strip()
    if clean_build_id != build_id or BUILD_ID_RE.fullmatch(clean_build_id) is None:
        raise ValueError(
            "build id must match github:<owner>/<repository>:<run_id>:<run_attempt>:<commit_sha>"
        )

    digest = hashlib.sha256(sbom.read_bytes()).hexdigest()
    return (
        '"""Generated by scripts/embed_build_info.py; do not edit in a release build."""\n\n'
        "from typing import Final\n\n"
        f"SBOM_SHA256: Final[str | None] = {digest!r}\n"
        f"BUILD_ID: Final[str | None] = {clean_build_id!r}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sbom", type=Path, required=True)
    parser.add_argument("--build-id", required=True)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    try:
        payload = render(args.sbom, args.build_id)
    except ValueError as exc:
        print(f"VIOLATION: {exc}")
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(payload, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(args.sbom.read_bytes()).hexdigest()
    print(f"embedded build facts: sbom sha256 {digest}; build id {args.build_id.strip()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
