"""The five-step pipeline between a model's reply and a human -- `04` §6.

```
GlueOutput(authored)
  -> 1. STATIC AUDIT   reject -> DISCARD, agent_output_rejected(rule), no file written
  -> 2. WRITE          .adopt/extractors/<id>.py and tests/test_<id>.py
  -> 3. SANDBOX RUN    crash/timeout -> quarantine_failed, file kept for the reviewer
  -> 4. FACTS          .adopt/out/quarantine/facts.json  -- NEVER the store
  -> 5. REVIEW ROW     .adopt/out/quarantine/review.json
```

**Step 1 runs before step 2, and the ordering is the security property.** A
module that fails the audit is never written to disk at all -- not to a scratch
path, not to a temp file, not "for the reviewer to see what was rejected". `04`
§6 says *"DISCARD, record `agent_output_rejected(rule)`. No file written."*, and
the rule that survives review pressure is the one where the rejected artefact
does not exist to be recovered.

**Nothing here can reach the store, and it is structural rather than careful.**
This module imports no writer, no port and no store handle; the only paths it
knows are under `.adopt/`. `01` F12.3's *"never to the store, until
`adopt extractors review <id> --approve`"* is therefore not a rule this code
follows -- it is a capability this code does not have. The same argument
`SurfaceFact` makes by having no `uri` field.

**`--approve` is refused when the file differs from the generated original.**
`04` §6 states why, and it is worth restating because it looks like friction and
is actually the measurement: without the refusal, a reviewer patches a module
into working order and approves it, the rewrite is never recorded, and ADR-0.1's
>40% reversal trigger can never fire. The digest of the generated bytes is
written beside the module at generation time, so the comparison does not depend
on the ledger being intact.
"""

import hashlib
import json
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final, Protocol

from adopt_map.agent_gate import (
    GateDecision,
    GateInputs,
    SampledFile,
    sample_digest,
    select_samples,
)
from adopt_map.agent_gate import evaluate as evaluate_gate
from adopt_map.fileindex import FileIndex
from adopt_map.plugins import audit_source
from adopt_map.review_ledger import LEDGER_FILENAME, ReviewEntry, append, now_iso
from adopt_map.sandbox import SandboxResult, run_module
from adopt_map.schemas.agent import GlueOutput, TriageOutput
from adopt_map.schemas.attributes import ATTRIBUTE_MODELS
from adopt_map.schemas.surface import SurfaceFact
from adopt_obs import AdoptError, ErrorCode, get_logger

__all__ = [
    "EXTRACTORS_DIRNAME",
    "QUARANTINE_DIRNAME",
    "GlueRunner",
    "QuarantineOutcome",
    "QuarantinePaths",
    "approve",
    "generated_digest",
    "quarantine",
    "reject",
    "rewrite",
    "run_glue_pass",
]

#: `04` §7's *"the active id per position lives in a module constant naming
#: `<id>/v<n>`"*, following Build 0's `DISAMBIGUATION_PROMPT_REF = "detect-001/v1"`.
#: **Rollback is repointing these**, which is why they are four names in one
#: module rather than four string literals at four call sites.
TRIAGE_PROMPT_REF: Final[str] = "map-triage-001/v1"
GLUE_PROMPT_REF: Final[str] = "map-glue-001/v1"
LABEL_PROMPT_REF: Final[str] = "map-label-001/v1"
PROSE_PROMPT_REF: Final[str] = "map-prose-001/v1"

_log = get_logger(__name__)

#: Where an agent-authored module lives while it waits for a human. `01` F12.4:
#: *"the agent may not touch ... any path outside `.adopt/extractors/`"*.
EXTRACTORS_DIRNAME: Final[str] = "extractors"

#: Where its facts and its review row go. `docs/pack/OPEN-DECISIONS.md` OD-15
#: takes the stated default and gitignores this (PRD Q5).
QUARANTINE_DIRNAME: Final[str] = "quarantine"

#: The sidecar carrying the digest of the bytes as generated. A separate file
#: rather than a line in the module, because a digest a reviewer can edit while
#: editing the module is a digest that always matches.
_DIGEST_SUFFIX: Final[str] = ".generated.sha256"


class GlueRunner(Protocol):
    """The one way this package reaches a model -- and it is a port, not an import.

    `adopt-map` does **not** depend on `adopt-agent`. It declares what it needs and
    is handed a realization by `adopt_cli`, exactly as `ports.py` does for storage
    (`docs/pack/OPEN-DECISIONS.md` OD-1/OD-2) and as `adopt_cli.commands.detect`
    already does for `adopt_detect`. Two consequences, both wanted: the glue pass
    is testable with a fake that opens no socket, and `04` §3's *"every call goes
    through Build 0's seam"* stays true without this package knowing what a seam
    is.

    `run` returns the **validated** output model. Validation belongs to the
    realization because `04` §5's one reparse retry is the runner's -- a caller
    that validated would either duplicate the retry or skip it.
    """

    def run(
        self, prompt_ref: str, inputs: dict[str, Any], *, model: type[Any]
    ) -> tuple[Any, float, float]:
        """`(output, cost_usd, elapsed_s)` for one prompt. Raises on a second schema failure."""
        ...


@dataclass(frozen=True, slots=True)
class QuarantinePaths:
    """The three directories a pass may write, derived from one `.adopt/` root."""

    adopt_dir: Path

    @property
    def extractors(self) -> Path:
        return self.adopt_dir / EXTRACTORS_DIRNAME

    @property
    def quarantine_out(self) -> Path:
        return self.adopt_dir / "out" / QUARANTINE_DIRNAME

    @property
    def ledger(self) -> Path:
        return self.adopt_dir / LEDGER_FILENAME

    def module(self, extractor_id: str) -> Path:
        return self.extractors / f"{extractor_id}.py"

    def test_module(self, extractor_id: str) -> Path:
        return self.extractors / "tests" / f"test_{extractor_id.replace('.', '_')}.py"

    def digest_sidecar(self, extractor_id: str) -> Path:
        return self.extractors / f"{extractor_id}{_DIGEST_SUFFIX}"


@dataclass(frozen=True, slots=True)
class QuarantineOutcome:
    """What one pass through the pipeline produced.

    `written` is `False` for every rejection, which is `04` §6 step 1's *"No file
    written"* expressed as a value a caller can assert on rather than a filesystem
    state a test has to go looking for.
    """

    extractor_id: str
    status: str
    written: bool = False
    audit_rules: tuple[str, ...] = ()
    fact_count: int = 0
    sandbox: SandboxResult | None = None
    review_path: Path | None = None


def generated_digest(source: str) -> str:
    """The digest recorded at generation and compared at approval."""
    return hashlib.sha256(source.encode("utf-8")).hexdigest()


def quarantine(
    output: GlueOutput,
    *,
    paths: QuarantinePaths,
    root: Path,
    samples: Sequence[SampledFile],
    decision: GateDecision,
    prompt_ref: str,
    adapter: str | None,
    cost_usd: float,
    truncated: int = 0,
    archetype: str = "web",
    tier: str | None = None,
) -> QuarantineOutcome:
    """Drive `04` §6's five steps over one authored module."""
    if output.outcome == "declined":
        _log.info("agent_declined", reason=output.decline_reason)
        return QuarantineOutcome(extractor_id="", status="declined")
    if output.extractor_id is None or output.module_source is None or output.manifest is None:
        raise AdoptError(
            ErrorCode.MAP_EXTRACTOR_FAILED,
            message="an authored GlueOutput carried no extractor_id, module source or manifest",
            hint="`04` §5's `authored` arm requires all three. A reply satisfying the "
            "schema but not the arm is a prompt defect, and a new prompt id is the fix.",
        )
    extractor_id = output.extractor_id

    # ---- step 1: static audit, before anything touches disk ------------------
    findings = audit_source(output.module_source, declared_kinds=output.manifest.kinds)
    if findings:
        rules = tuple(sorted({finding.rule for finding in findings}))
        _log.error("agent_output_rejected", extractor=extractor_id, audit_rules=list(rules))
        return QuarantineOutcome(
            extractor_id=extractor_id, status="rejected", written=False, audit_rules=rules
        )

    # ---- step 2: write ------------------------------------------------------
    paths.extractors.mkdir(parents=True, exist_ok=True)
    paths.module(extractor_id).write_text(output.module_source, encoding="utf-8")
    paths.digest_sidecar(extractor_id).write_text(
        generated_digest(output.module_source), encoding="utf-8"
    )
    if output.test_source is not None:
        paths.test_module(extractor_id).parent.mkdir(parents=True, exist_ok=True)
        paths.test_module(extractor_id).write_text(output.test_source, encoding="utf-8")

    # ---- step 3: sandbox ----------------------------------------------------
    result = run_module(
        paths.module(extractor_id),
        root=root,
        sampled_paths=[sample.path for sample in samples],
        archetype=archetype,
        tier=tier,
    )
    if not result.usable:
        _log.warn("quarantine_failed", extractor=extractor_id, sandbox_status=result.status)

    # ---- step 4: facts, to quarantine and nowhere else ----------------------
    paths.quarantine_out.mkdir(parents=True, exist_ok=True)
    facts = list(result.facts)
    _write_json(paths.quarantine_out / "facts.json", {"extractor_id": extractor_id, "facts": facts})

    # ---- step 5: review row -------------------------------------------------
    review = {
        "extractor_id": extractor_id,
        "sampled_files": [sample.path for sample in samples],
        "sampled_truncated": [sample.path for sample in samples if sample.truncated],
        "samples_omitted": truncated,
        "sample_digest": sample_digest(samples),
        "fact_count": len(facts),
        "sample_facts": facts[:_SAMPLE_FACTS],
        "audit_result": "clean",
        "sandbox_result": result.status,
        "sandbox_error": result.error,
        "egress_attempts": result.egress_attempts,
        "cost_usd": cost_usd,
        "adapter": adapter,
        "prompt_id": prompt_ref,
        "unreached_families": list(decision.unreached_families),
        "trace_ref": None,
    }
    review_path = paths.quarantine_out / "review.json"
    _write_json(review_path, review)

    append(
        paths.ledger,
        ReviewEntry(
            ts=now_iso(),
            extractor_id=extractor_id,
            outcome="quarantined",
            module_sha256=generated_digest(output.module_source),
            prompt_ref=prompt_ref,
            adapter=adapter,
        ),
    )
    return QuarantineOutcome(
        extractor_id=extractor_id,
        status="quarantined",
        written=True,
        fact_count=len(facts),
        sandbox=result,
        review_path=review_path,
    )


#: How many facts the review row carries inline. A reviewer needs a sense of what
#: the module produces, not the whole output -- `facts.json` beside it has all of
#: them, and a review row nobody scrolls to the end of is a review row nobody
#: reads.
_SAMPLE_FACTS: Final[int] = 5  # const-sync: ok -- a display cap on a review row


def approve(paths: QuarantinePaths, extractor_id: str) -> None:
    """Accept a module **only if its bytes are the generated bytes**. `04` §6.

    Raises:
        AdoptError: ``MAP_USAGE`` when the file differs, naming `--rewrite`. This
            is the refusal ADR-0.1's reversal trigger depends on: an approval that
            silently absorbed a human's edit would make the rewrite rate a
            measurement of nothing.
    """
    module = paths.module(extractor_id)
    sidecar = paths.digest_sidecar(extractor_id)
    if not module.is_file() or not sidecar.is_file():
        raise AdoptError(
            ErrorCode.MAP_USAGE,
            message=f"{extractor_id} is not in quarantine",
            hint="Run `adopt extractors list` to see what is awaiting review.",
        )
    current = generated_digest(module.read_text(encoding="utf-8"))
    if current != sidecar.read_text(encoding="utf-8").strip():
        raise AdoptError(
            ErrorCode.MAP_USAGE,
            message=f"{extractor_id} has been modified since it was generated",
            hint="Use `adopt extractors review <id> --rewrite` instead. `04` §6 refuses "
            "--approve on a modified file on purpose: the rewrite rate is what "
            "ADR-0.1's reversal trigger reads, and an approval that absorbed an "
            "edit would hide exactly the signal the mechanism exists to produce.",
        )
    _record(paths, extractor_id, "approved", module)


def rewrite(paths: QuarantinePaths, extractor_id: str, *, reason: str | None = None) -> None:
    """Record that a human modified the module before accepting it."""
    module = paths.module(extractor_id)
    if not module.is_file():
        raise AdoptError(
            ErrorCode.MAP_USAGE,
            message=f"{extractor_id} is not in quarantine",
            hint="Run `adopt extractors list` to see what is awaiting review.",
        )
    _record(paths, extractor_id, "rewritten", module, reason=reason)


def reject(paths: QuarantinePaths, extractor_id: str, *, reason: str) -> None:
    """Delete the module with a reason. The ledger entry outlives the file."""
    module = paths.module(extractor_id)
    if not module.is_file():
        raise AdoptError(
            ErrorCode.MAP_USAGE,
            message=f"{extractor_id} is not in quarantine",
            hint="Run `adopt extractors list` to see what is awaiting review.",
        )
    digest = generated_digest(module.read_text(encoding="utf-8"))
    module.unlink()
    paths.digest_sidecar(extractor_id).unlink(missing_ok=True)
    append(
        paths.ledger,
        ReviewEntry(
            ts=now_iso(),
            extractor_id=extractor_id,
            outcome="rejected",
            module_sha256=digest,
            reason=reason,
        ),
    )


def _record(
    paths: QuarantinePaths,
    extractor_id: str,
    outcome: str,
    module: Path,
    *,
    reason: str | None = None,
) -> None:
    append(
        paths.ledger,
        ReviewEntry(
            ts=now_iso(),
            extractor_id=extractor_id,
            outcome=outcome,
            module_sha256=generated_digest(module.read_text(encoding="utf-8")),
            reason=reason,
        ),
    )


def _write_json(path: Path, payload: object) -> None:
    """Sorted keys, LF, trailing newline -- the `02` §9 rendering rule.

    The same rule the export writer follows, for the same reason: an artefact
    whose bytes depend on dict ordering is an artefact two runs disagree about.
    """
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def run_glue_pass(
    runner: GlueRunner,
    *,
    inputs_gate: GateInputs,
    index: FileIndex,
    paths: QuarantinePaths,
    root: Path,
    adapter: str | None,
    extractor_ids: Sequence[str],
) -> QuarantineOutcome:
    """The whole pass: gate, sample, triage, author, quarantine. `04` §2 -> §6.

    **The gate is asked first and its refusal is returned, not raised.** A refused
    pass is `04` §2's *"normal, successful run"*, so this returns an outcome whose
    status names the failing condition and whose `written` is false -- the caller
    prints it and exits 0 with the deterministic map it already has.

    **Budget is spent after each call, never reserved before one.** `04` §7's
    ceilings abort the pass at exit 6 *"with the deterministic map intact"*, and
    the `AdoptError` that carries `MAP_AGENT_BUDGET_EXHAUSTED` propagates to the
    CLI, which has already written and committed everything deterministic.
    """
    decision = evaluate_gate(inputs_gate)
    if not decision.allowed:
        decision.record()
        return QuarantineOutcome(extractor_id="", status=f"skipped:{decision.failed}")

    budget = inputs_gate.budget
    if budget is None:  # pragma: no cover -- G-4 already refused this case
        message = "the gate admitted a pass with no budget"
        raise AssertionError(message)

    samples, omitted = select_samples(index)
    budget.spend(files=len(samples))

    triage, cost, elapsed = runner.run(
        TRIAGE_PROMPT_REF,
        {
            "coverage_report_json": json.dumps(dict(inputs_gate.facts_by_kind), sort_keys=True),
            "unmatched_paths": "\n".join(sample.path for sample in samples),
            "extractor_manifest_ids": ", ".join(sorted(extractor_ids)),
            "archetype": inputs_gate.archetype,
        },
        model=TriageOutput,
    )
    budget.spend(usd=cost, seconds=elapsed)

    families = [item for item in triage.families if item.statically_recoverable]
    if not families:
        _log.info("agent_triage_empty", families=len(triage.families))
        return QuarantineOutcome(extractor_id="", status="no_family")
    # Highest value first, then by name -- a tie broken by ranking alone would
    # make the pass a function of dict order, which `02` §7 obligation 3 forbids
    # of an extractor and this pass has no better claim to.
    target = sorted(families, key=lambda item: (-item.value_rank, item.family))[0]

    glue, cost, elapsed = runner.run(
        GLUE_PROMPT_REF,
        {
            "extractor_protocol_source": _protocol_source(),
            "surface_fact_schema": json.dumps(SurfaceFact.model_json_schema(), sort_keys=True),
            "per_kind_conventions": ", ".join(sorted(target.identity_kinds)),
            "attribute_registry": json.dumps(sorted(ATTRIBUTE_MODELS), sort_keys=True),
            "family_description": f"{target.family}: {target.rationale}",
            "sampled_files": "\n\n".join(f"### {sample.path}\n{sample.text}" for sample in samples),
        },
        model=GlueOutput,
    )
    budget.spend(usd=cost, seconds=elapsed)

    return quarantine(
        glue,
        paths=paths,
        root=root,
        samples=samples,
        decision=decision,
        prompt_ref=GLUE_PROMPT_REF,
        adapter=adapter,
        cost_usd=budget.spent_usd,
        truncated=omitted,
        archetype=inputs_gate.archetype,
        tier=inputs_gate.tier,
    )


def _protocol_source() -> str:
    """The `Extractor` protocol's own source, sent verbatim to `map-glue-001`.

    `04` §4.2 promises the model *"the Extractor protocol"*, and reading it from
    the module is what keeps that promise true after the protocol changes. A
    hand-maintained copy in a prompt input would be a second declaration of a
    shape `02` §7 owns -- and the one the model actually writes against.
    """
    import inspect

    from adopt_map.schemas.surface import Extractor

    return inspect.getsource(Extractor)
